server:
  port: 8081
spring:
  application:
    name: jetty-test-app
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/jetty-test-db
    username: sa
    password:
  jpa:
    platform: org.hibernate.dialect.H2Dialect
    show_sql: false
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2
logging:
  level:
    org.hibernate.SQL: DEBUG
    com.example.app: DEBUG
